export interface QuickMed {
  id: string;
  name: string;
  class: string;
  onLabel: string;
  offLabel: string;
  mechanism: string;
  onset: string;
  effects: string;
  contra: string;
  interactions: string;
  tip: string;
  source?: string;
}

export interface QuickMedModule {
  name: string;
  medications: QuickMed[];
}

export const quickMedModules: QuickMedModule[] = [
  {
    name: 'Antidepressivos',
    medications: [
      {
        id: 'fluoxetina',
        name: 'Fluoxetina (Prozac®, Daforin®...)',
        class: 'ISRS',
        onLabel: 'Depressão, TOC, bulimia, TDPM',
        offLabel: 'PTSD, TDH, ejac. precoce',
        mechanism: '↑5-HT sináptica',
        onset: '2-4 sem',
        effects: 'Náusea, insônia, disfunção sexual',
        contra: 'IMAO, QT longo',
        interactions: 'Tramadol (↑serotonina), varfarina',
        tip: 'Peso + ativar cedo (agita)',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'sertralina',
        name: 'Sertralina (Zoloft®, Assert®)',
        class: 'ISRS',
        onLabel: 'Depressão, TOC, TP, TDPM',
        offLabel: 'Ansiedade social em dose alta',
        mechanism: '↑5-HT, leve ↑DA (NAcc)',
        onset: '2 sem',
        effects: 'Diarreia, tremor, queda libido',
        contra: 'IMAO',
        interactions: 'AINEs ↑sangramento',
        tip: 'Ideal p/ cardiopata (menor QT)',
        source: 'pt.wikipedia.org',
      },
      {
        id: 'paroxetina',
        name: 'Paroxetina (Paxil®, Pondera®)',
        class: 'ISRS',
        onLabel: 'Depressão, TAG, TP, TOC, TEP',
        offLabel: 'Ondas de calor (climatério)',
        mechanism: '↑5-HT forte, leve ACh-1',
        onset: '1-3 sem',
        effects: 'Sonolência, ganho peso',
        contra: 'Gravidez (malf. cardíaca)',
        interactions: 'Tamoxifeno ↓eficácia',
        tip: 'Síndrome retirada: taper lento',
      },
      {
        id: 'citalopram',
        name: 'Citalopram (Cittá®)',
        class: 'ISRS',
        onLabel: 'Depressão',
        offLabel: 'Ansiedade',
        mechanism: '↑5-HT',
        onset: '2-4 sem',
        effects: 'QT↑ dose-depend.',
        contra: 'Arritmia prévia',
        interactions: 'Omeprazol ↑nível',
        tip: 'ECG se dose > 40 mg',
      },
      {
        id: 'escitalopram',
        name: 'Escitalopram (Lexapro®)',
        class: 'ISRS',
        onLabel: 'Depressão, TAG',
        offLabel: 'TOC',
        mechanism: '↑5-HT (enantiômero S)',
        onset: '1-2 sem',
        effects: 'Dor cabeça, GI leve',
        contra: 'IMAO',
        interactions: 'QT↑ em > 20 mg',
        tip: 'Start 5 mg em idoso',
      },
      {
        id: 'fluvoxamina',
        name: 'Fluvoxamina (Luvox®)',
        class: 'ISRS',
        onLabel: 'TOC',
        offLabel: 'Depressão, TAG, TUS',
        mechanism: '↑5-HT + forte inib. CYP1A2',
        onset: '2-3 sem',
        effects: 'Sedação, ⬆️enz. hepát.',
        contra: 'Clozapina ↑nível',
        interactions: 'Cafeína, teofilina ↑nível',
        tip: 'Avaliar TGO/TGP 6/6 m',
      },
      {
        id: 'venlafaxina',
        name: 'Venlafaxina (Efexor XR®)',
        class: 'ISRSN',
        onLabel: 'Depressão, TAG, TP',
        offLabel: 'Dor neuropática, menopausa',
        mechanism: '↑5-HT; ↑NA > 150 mg',
        onset: '1-2 sem',
        effects: 'PA↑, sudorese',
        contra: 'HAS não controlada',
        interactions: 'IMAO, triptanos',
        tip: 'Checar PA + eletrólitos',
      },
      {
        id: 'desvenlafaxina',
        name: 'Desvenlafaxina (Pristiq®)',
        class: 'ISRSN',
        onLabel: 'Depressão',
        offLabel: 'Dor crônica',
        mechanism: 'Igual venlafaxina (metab.)',
        onset: '1 sem',
        effects: 'HTN, náusea',
        contra: 'HAS grave',
        interactions: 'Sertralina',
        tip: 'PA e lipidograma',
      },
      {
        id: 'duloxetina',
        name: 'Duloxetina (Cymbalta®, Velija®)',
        class: 'ISRSN',
        onLabel: 'Depressão, TAG, dor neuropática',
        offLabel: 'Fibromialgia',
        mechanism: '↑5-HT + NA',
        onset: '1-2 sem',
        effects: 'Boca seca, sudorese',
        contra: 'IR grave, Hepatite',
        interactions: 'Etanol ↑hepatotox.',
        tip: 'TGO/TGP antes & 3/12',
      },
      {
        id: 'bupropiona',
        name: 'Bupropiona (Wellbutrin®, Bup®)',
        class: 'NDRI',
        onLabel: 'Depressão, cessar tabaco',
        offLabel: 'TDAH adulto, obesidade',
        mechanism: '↑DA + NA',
        onset: '1-2 sem',
        effects: 'Insônia, ↓apetite',
        contra: 'Convulsão, bulimia',
        interactions: 'ISRS + bup → ↓limiar conv.',
        tip: 'Evitar >450 mg/dia',
        source: 'gov.br',
      },
      {
        id: 'mirtazapina',
        name: 'Mirtazapina (Remeron®)',
        class: 'NaSSA',
        onLabel: 'Depressão',
        offLabel: 'Insônia, caquexia',
        mechanism: 'Antag. α2 + 5-HT2/3',
        onset: '1 sem',
        effects: 'Sonolência, ganho peso',
        contra: 'Agranulocitose rara',
        interactions: 'BZD sedativos',
        tip: 'Hemograma se febre',
      },
      {
        id: 'trazodona',
        name: 'Trazodona (Donaren®)',
        class: 'SARI',
        onLabel: 'Depressão',
        offLabel: 'Insônia, ansiedade',
        mechanism: 'Antag. 5-HT2 + recapt. 5-HT',
        onset: '1 sem',
        effects: 'Sedação, hipotensão, priapismo',
        contra: 'Pós-IAM recente',
        interactions: 'Anti-HTN',
        tip: 'Abaixar dose em idoso',
      },
      {
        id: 'agomelatina',
        name: 'Agomelatina (Valdoxan®)',
        class: 'MT1/2 ago + 5-HT2c antag.',
        onLabel: 'Depressão',
        offLabel: 'Ritmo circadiano',
        mechanism: 'Reajusta ritmo melatonina',
        onset: '2-4 sem',
        effects: 'Eleva TGO/TGP',
        contra: 'IHF',
        interactions: 'Fluconazol ↑nível',
        tip: 'Função hepática basal + 6/6 sem',
      },
      {
        id: 'vortioxetina',
        name: 'Vortioxetina (Brintellix®)',
        class: 'Modulador 5-HT',
        onLabel: 'Depressão',
        offLabel: 'Declínio cognitivo',
        mechanism: 'Inib. SERT + ago/antag 5-HT',
        onset: '2 sem',
        effects: 'Nausea, prurido',
        contra: 'IMAO',
        interactions: 'Rifampicina ↓nível',
        tip: 'Dose única diária, sem refeições',
      },
      {
        id: 'tianeptina',
        name: 'Tianeptina (Stablon®)',
        class: 'Modulador glut-/opioide',
        onLabel: 'Depressão',
        offLabel: 'Distimia',
        mechanism: '↑recapit. 5-HT (atípico)',
        onset: '2-4 sem',
        effects: 'Constipação, sonolência',
        contra: 'Abuso alto',
        interactions: 'EtOH ↑sedação',
        tip: 'Monitorar uso por dependência',
      },
      {
        id: 'amitriptilina',
        name: 'Amitriptilina (Tryptanol®)',
        class: 'TCA',
        onLabel: 'Depressão, dor neuropática',
        offLabel: 'Enurese, profilaxia migrânea',
        mechanism: 'Bloq. 5-HT/NA + anti-ACh',
        onset: '2-4 sem',
        effects: 'Sedação, ganho peso, QT↑',
        contra: 'IAM recente',
        interactions: 'Anti-H1, ISRS',
        tip: 'ECG antes de dose alta',
        source: 'abp.org.br',
      },
      {
        id: 'nortriptilina',
        name: 'Nortriptilina (Pamelor®)',
        class: 'TCA',
        onLabel: 'Depressão',
        offLabel: 'Dor neuropática',
        mechanism: 'Igual, mas \u2193ACh',
        onset: '2 sem',
        effects: 'Tremor, boca seca',
        contra: 'IH grave',
        interactions: 'Linezolida',
        tip: 'Monitorar nível (50-150 ng/mL)',
      },
      {
        id: 'imipramina',
        name: 'Imipramina (Tofranil®)',
        class: 'TCA',
        onLabel: 'Depressão',
        offLabel: 'Enurese infantil',
        mechanism: 'Igual amitriptilina',
        onset: '2-4 sem',
        effects: 'Arritmia, ortostase',
        contra: 'ICC, glaucoma',
        interactions: 'B-block ↑QT',
        tip: 'ECG + PA',
      },
      {
        id: 'clomipramina',
        name: 'Clomipramina (Anafranil®)',
        class: 'TCA',
        onLabel: 'TOC',
        offLabel: 'Depressão, ejacul. precoce',
        mechanism: '5-HT > NA',
        onset: '2-3 sem',
        effects: 'Sudorese, convulsão',
        contra: 'IH',
        interactions: 'Lítio ↑serot.',
        tip: 'Nível sérico (175-300 ng/mL)',
      },
      {
        id: 'moclobemida',
        name: 'Moclobemida (Aurorix®)',
        class: 'IMAO-A revers.',
        onLabel: 'Depressão atípica, fobia social',
        offLabel: 'Distimia',
        mechanism: 'Inibe MAO-A reversível',
        onset: '<1 sem',
        effects: 'Insônia, cefaleia',
        contra: 'IMAO não selet., feocromocit.',
        interactions: 'Tiramina (crise HTN)',
        tip: 'Dieta tiramina light, mas menos rígida',
      },
    ],
  },
  {
    name: 'Antipsicóticos 2ª/3ª geração',
    medications: [
      {
        id: 'clozapina',
        name: 'Clozapina (Leponex®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia refratária; ↓risco suicídio',
        offLabel: 'TR bipolar, agressão refratária',
        mechanism: 'Bloq. D4 > D2 + 5-HT2A',
        onset: '1-2 sem',
        effects: 'Sialorreia, sedação, ganho peso, agranulocitose',
        contra: 'Neutropenia, convulsão não controlada',
        interactions: 'Carbamazepina (↑ aplasia)',
        tip: 'Hemograma semanal 6 m → mensal',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'risperidona',
        name: 'Risperidona (Risperdal®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, mania bipolar, irritab. autismo',
        offLabel: 'Demência (agitação) – controverso',
        mechanism: 'D2 + 5-HT2A bloqueio',
        onset: '1-2 sem',
        effects: '↑Prolactina, EPS, ganho peso',
        contra: 'Demência CV/AVC',
        interactions: 'Carbamazepina ↓nível',
        tip: 'Prolactina + peso cada 3-6 m',
        source: 'cellerafarma.com.br',
      },
      {
        id: 'paliperidona',
        name: 'Paliperidona (Invega®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, esquizoafetivo',
        offLabel: 'Bipolar (off)',
        mechanism: 'D2/5-HT2A bloqueio, via renal',
        onset: '1-2 sem',
        effects: '↑Prolactina, QT↑',
        contra: 'IR grave',
        interactions: 'QT-drugs, carbamaz.',
        tip: 'Ver ECG inicial',
        source: 'innovativemedicine.jnj.com',
      },
      {
        id: 'olanzapina',
        name: 'Olanzapina (Zyprexa®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, bipolar',
        offLabel: 'Anorexia, agitação',
        mechanism: 'D2 + 5-HT2A + hist.',
        onset: '1-2 sem',
        effects: 'Ganho peso, dislipid., sedação',
        contra: 'DM2 mal control.',
        interactions: 'BDZ IM (dep. resp)',
        tip: 'Peso, glicemia, lipídeos 3/3 m',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'quetiapina',
        name: 'Quetiapina (Seroquel®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, bipolar, adj. MDD',
        offLabel: 'Insônia low-dose',
        mechanism: 'Bloq. 5-HT2A > D2; H1 forte',
        onset: '<1 sem p/ sono; 2 sem p/ humor',
        effects: 'Sedação, ortostase, ganho peso',
        contra: 'IH grave',
        interactions: 'QT-drugs, inib. CYP3A4',
        tip: 'PA ortostática; efeito travesseiro',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'ziprasidona',
        name: 'Ziprasidona (Geodon®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, mania aguda, manutenção bipolar',
        offLabel: 'Depressão adj.',
        mechanism: 'D2/5-HT2A bloqueio + 5-HT1A ago',
        onset: '1 sem',
        effects: 'Akatisia, QT↑, náusea',
        contra: 'QT longo',
        interactions: 'Macrolídeos, antiarrítmicos',
        tip: 'Tomar com >500 kcal; ECG inicial',
        source: 'viatris.com.br',
      },
      {
        id: 'aripiprazol',
        name: 'Aripiprazol (Abilify®)',
        class: 'Parcial D2/5-HT1A',
        onLabel: 'Esquizofrenia, bipolar, adj. MDD, autismo',
        offLabel: 'OCD augmentation, impulsividade',
        mechanism: '"Estabilizador D2" parcial',
        onset: '1 sem',
        effects: 'Akatisia, insônia, impulso gamble',
        contra: 'Psicose aguda não avaliada',
        interactions: 'Inib./indut. CYP3A4/2D6',
        tip: 'Checar comportamento compulsivo',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'brexpiprazol',
        name: 'Brexpiprazol (Rexulti®)',
        class: 'Parcial D2/5-HT1A',
        onLabel: 'Esquizofrenia',
        offLabel: 'Adj. MDD, agitação demência',
        mechanism: 'Parecido aripip., mas ↓akatisia',
        onset: '1-2 sem',
        effects: 'Aumento peso leve, sedação',
        contra: 'Demência AV',
        interactions: 'CYP3A4/2D6',
        tip: 'Peso + sono; menor EPS',
        source: 'portaltj.tjrj.jus.br',
      },
      {
        id: 'lurasidona',
        name: 'Lurasidona (Latuda®)',
        class: 'SDA',
        onLabel: 'Esquizofrenia, depressão bipolar',
        offLabel: 'MDD adj.',
        mechanism: 'D2/5-HT2A + 5-HT7 antag.',
        onset: '1 sem',
        effects: 'Náusea, akatisia leve, pouco ganho peso',
        contra: 'IH moder-grave',
        interactions: 'Ketoconazol ↑nível',
        tip: 'Tomar com comida ≥350 kcal',
        source: 'leonardopalmeira.com.br',
      },
      {
        id: 'asenapina',
        name: 'Asenapina (Saphris®)',
        class: 'SDA sublingual',
        onLabel: 'Esquizofrenia, mania bipolar',
        offLabel: 'Tr. esquizoafetivo',
        mechanism: 'D2/5-HT2A bloq., H1 forte',
        onset: '1 sem',
        effects: 'Hipoestesia bucal, sedação, ganho peso',
        contra: 'IH grave',
        interactions: 'QT-drugs',
        tip: 'Sublingual: não comer/beber 10 min',
        source: 'drogariasaopaulo.com.br',
      },
    ],
  },
  {
    name: 'Ansiolíticos & Hipnóticos',
    medications: [
      {
        id: 'diazepam',
        name: 'Diazepam (Valium®)',
        class: 'BZD longa',
        onLabel: 'Ansiedade, espasmo, convulsão, pré-op',
        offLabel: 'Síndrome alcoólica, tetania',
        mechanism: '↑GABA-A (Cl-)',
        onset: '15-30 min VO',
        effects: 'Sedação, amnésia, ataxia',
        contra: 'Miastenia, apneia sono',
        interactions: 'Álcool, opioides',
        tip: 'Evitar volante <8 h; t½ ≈ 48 h',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'clonazepam',
        name: 'Clonazepam (Rivotril®)',
        class: 'BZD longa',
        onLabel: 'Epilepsia, pânico, ansiedade',
        offLabel: 'Tique/Tourette',
        mechanism: '↑GABA-A',
        onset: '30-60 min',
        effects: 'Sonolência, ataxia, salivação',
        contra: 'I.H. grave',
        interactions: 'Depressores SNC',
        tip: 'Dose micro (<0,5 mg) pra ansiedade leve',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'alprazolam',
        name: 'Alprazolam (Frontal®)',
        class: 'BZD intermediária',
        onLabel: 'TAG, pânico',
        offLabel: 'Tinnitus, PMS',
        mechanism: '↑GABA-A',
        onset: '30 min',
        effects: 'Dependência, sonolência',
        contra: 'Glaucoma agudo, IMAO',
        interactions: 'Claritro ↑nível',
        tip: 'Uso crônico >3 m? Planeje taper',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'lorazepam',
        name: 'Lorazepam (Ativan®)',
        class: 'BZD interm-curta',
        onLabel: 'Ansiedade, agitação psicótica adj.',
        offLabel: 'Delirium (hospital)',
        mechanism: '↑GABA-A',
        onset: '20-30 min',
        effects: 'Sedação forte, hipotensão',
        contra: 'I.R. grave',
        interactions: 'Opioides, álcool',
        tip: 'Bom p/ idoso (sem metab. ativo)',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'bromazepam',
        name: 'Bromazepam (Lexotan®)',
        class: 'BZD interm.',
        onLabel: 'Ansiedade, tensão',
        offLabel: 'Insônia de início',
        mechanism: '↑GABA-A',
        onset: '30-60 min',
        effects: 'Boca seca, fadiga',
        contra: 'Miastenia, I.R.',
        interactions: 'Álcool',
        tip: 'Começar 1,5 mg noite; checar risco queda',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'midazolam',
        name: 'Midazolam (VO)',
        class: 'BZD curta hipnótica',
        onLabel: 'Insônia aguda, pré-op',
        offLabel: 'Sedação endoscopia',
        mechanism: '↑GABA-A',
        onset: '10-20 min',
        effects: 'Amnésia anterógrada, depressão resp.',
        contra: 'Idoso frágil',
        interactions: 'Cetoconazol ↑nível',
        tip: 'Usar 7,5 mg máx. em 60+ anos',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'flunitrazepam',
        name: 'Flunitrazepam (Rohypnol®)',
        class: 'BZD hipnótica',
        onLabel: 'Insônia severa (uso hospitalar)',
        offLabel: 'Pré-op',
        mechanism: '↑GABA-A',
        onset: '15-25 min',
        effects: 'Sedação profunda, amnésia',
        contra: 'Depressão resp., grávidas',
        interactions: 'Álcool (efeito “date-rape”)',
        tip: 'Vendido só com Rx A3; reavaliar em 14 dias',
        source: 'en.wikipedia.org',
      },
      {
        id: 'zolpidem',
        name: 'Zolpidem (Stilnox®)',
        class: 'Z-drug',
        onLabel: 'Insônia até 4 sem',
        offLabel: 'Jet-lag',
        mechanism: 'Agon. GABA-α1',
        onset: '15 min',
        effects: 'Sonambulismo, gosto amargo',
        contra: 'Depressão resp.',
        interactions: 'BZD, álcool',
        tip: 'Tomar deitado; mulher ↓dose',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'buspirona',
        name: 'Buspirona (Ansitec®)',
        class: 'Azapirona 5-HT1A',
        onLabel: 'TAG',
        offLabel: 'Ansiedade pré-menopausa',
        mechanism: 'Parcial ago 5-HT1A',
        onset: '1-3 sem',
        effects: 'Tontura, náusea',
        contra: 'IMAO, IH grave',
        interactions: 'IMAO, tramadol',
        tip: 'Sem sedação; bom p/ uso crônico',
        source: 'consultaremedios.com.br',
      },
      {
        id: 'hydroxyzine',
        name: 'Hydroxyzine (Pergo®)',
        class: 'Anti-H1',
        onLabel: 'Prurido',
        offLabel: 'Ansiedade leve, insônia',
        mechanism: 'H1 antag.; sedativo',
        onset: '30 min',
        effects: 'Boca seca, sedação',
        contra: 'Porfiria, gravidez 1º tri',
        interactions: 'Álcool, BZD',
        tip: 'Útil PRN p/ crise; sem dependência',
        source: 'eurofarma.com.br',
      },
      {
        id: 'pregabalina',
        name: 'Pregabalina (Lyrica®)',
        class: 'α2-δ lig.',
        onLabel: 'Dor neuropática, epilepsia',
        offLabel: 'TAG (on-label BR)',
        mechanism: '↓liberação glut/NA',
        onset: '1-2 sem',
        effects: 'Tontura, ganho peso',
        contra: 'IH grave, edema',
        interactions: 'Opioides ↑sedação',
        tip: 'Risco abuso baixo-médio; tapear devagar',
        source: 'consultaremedios.com.br',
      },
    ],
  }
];
